<a href="https://colab.research.google.com/github/abhinay-2006/Generative_AI_2025/blob/main/2303A52228_7_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
url = "https://drive.google.com/uc?export=download&id=1AcdENlVm5dccNyo_vgdMbneX8YVvH5R3"
df = pd.read_csv(url)
print(df.dtypes)
for col in df.columns:
    if df[col].dtype == 'object':
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

price                int64
area                 int64
bedrooms             int64
bathrooms            int64
stories              int64
mainroad            object
guestroom           object
basement            object
hotwaterheating     object
airconditioning     object
parking              int64
prefarea            object
furnishingstatus    object
dtype: object


In [3]:
model = Sequential([
    Dense(8, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(16, activation='relu'),
    Dense(20, activation='relu'),
    Dense(10, activation='relu'),
    Dense(1, activation='sigmoid')
])
model.compile(optimizer='adadelta', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=150, batch_size=64, validation_data=(X_test, y_test))
model.save("diabetes_ann_model.h5")
loaded_model = keras.models.load_model("diabetes_ann_model.h5")
y_pred = (loaded_model.predict(X_test) > 0.5).astype(int)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print(f"Test Accuracy: {accuracy * 100:.2f}%")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 3s 92ms/step - accuracy: 0.2461 - loss: 0.7488 - val_accuracy: 0.2661 - val_loss: 0.7609
Epoch 2/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.2452 - loss: 0.7509 - val_accuracy: 0.2661 - val_loss: 0.7609
Epoch 3/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.2352 - loss: 0.7464 - val_accuracy: 0.2661 - val_loss: 0.7608
Epoch 4/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.2690 - loss: 0.7474 - val_accuracy: 0.2661 - val_loss: 0.7607
Epoch 5/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.2685 - loss: 0.7485 - val_accuracy: 0.2661 - val_loss: 0.7607
Epoch 6/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.2203 - loss: 0.7587 - val_accuracy: 0.2661 - val_loss: 0.7606
Epoch 7/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.2534 - loss: 0.7518 - val_accuracy: 0.2661 - val_loss: 0.7605
Epoch 8/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.2802 - loss: 0.7459 - val_accuracy: 0.2661 - val_loss:

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
Test Accuracy: 26.61%

Confusion Matrix:
[[26  3  0]
 [36  3  0]
 [36  5  0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.27      0.90      0.41        29
           1       0.27      0.08      0.12        39
           2       0.00      0.00      0.00        41

    accuracy                           0.27       109
   macro avg       0.18      0.32      0.18       109
weighted avg       0.17      0.27      0.15       109



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
